<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.14.1</Version>
    <Company>muller-camille</Company>
    <Product>CyberArkTerm</Product>
  </PropertyGroup>
</Project>
