//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberArkTerm.Core.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberArkTerm.Core.Localization.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account has no target address..
        /// </summary>
        public static string AccountHasNoAddress {
            get {
                return ResourceManager.GetString("AccountHasNoAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account has no user name..
        /// </summary>
        public static string AccountHasNoUser {
            get {
                return ResourceManager.GetString("AccountHasNoUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication cancelled..
        /// </summary>
        public static string AuthenticationCancelled {
            get {
                return ResourceManager.GetString("AuthenticationCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character not allowed in {0}: “{1}”..
        /// </summary>
        public static string CharacterNotAllowed {
            get {
                return ResourceManager.GetString("CharacterNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allowed machines.
        /// </summary>
        public static string ColumnAllowedMachines {
            get {
                return ResourceManager.GetString("ColumnAllowedMachines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ColumnCreated {
            get {
                return ResourceManager.GetString("ColumnCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string ColumnDomain {
            get {
                return ResourceManager.GetString("ColumnDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string ColumnPlatform {
            get {
                return ResourceManager.GetString("ColumnPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string ColumnSafe {
            get {
                return ResourceManager.GetString("ColumnSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ColumnServer {
            get {
                return ResourceManager.GetString("ColumnServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control characters are not allowed in the path..
        /// </summary>
        public static string ControlCharacterInPath {
            get {
                return ResourceManager.GetString("ControlCharacterInPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A folder cannot be moved into itself..
        /// </summary>
        public static string FolderIntoItself {
            get {
                return ResourceManager.GetString("FolderIntoItself", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string GroupNotSet {
            get {
                return ResourceManager.GetString("GroupNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid folder name..
        /// </summary>
        public static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string KindDatabase {
            get {
                return ResourceManager.GetString("KindDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string KindNetwork {
            get {
                return ResourceManager.GetString("KindNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string KindOther {
            get {
                return ResourceManager.GetString("KindOther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System language.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password for {0}:.
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        public static string PasswordPromptTitle {
            get {
                return ResourceManager.GetString("PasswordPromptTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the PSMP address.
        /// </summary>
        public static string PsmpAddressWhat {
            get {
                return ResourceManager.GetString("PsmpAddressWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid PVWA address: “{0}”..
        /// </summary>
        public static string PvwaAddressInvalid {
            get {
                return ResourceManager.GetString("PvwaAddressInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA address is required..
        /// </summary>
        public static string PvwaAddressRequired {
            get {
                return ResourceManager.GetString("PvwaAddressRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty response from the PVWA..
        /// </summary>
        public static string PvwaEmptyResponse {
            get {
                return ResourceManager.GetString("PvwaEmptyResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA must be reached over HTTPS: your credentials go through this connection..
        /// </summary>
        public static string PvwaHttpsRequired {
            get {
                return ResourceManager.GetString("PvwaHttpsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No session is open on the PVWA..
        /// </summary>
        public static string PvwaNoSession {
            get {
                return ResourceManager.GetString("PvwaNoSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from the PVWA: no session token received..
        /// </summary>
        public static string PvwaNoToken {
            get {
                return ResourceManager.GetString("PvwaNoToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA returned an HTML5 connection (PSM Gateway) instead of an RDP file..
        /// </summary>
        public static string RdpGatewayInstead {
            get {
                return ResourceManager.GetString("RdpGatewayInstead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from the PVWA{0}: no RDP file..
        /// </summary>
        public static string RdpUnexpected {
            get {
                return ResourceManager.GetString("RdpUnexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The root cannot be deleted..
        /// </summary>
        public static string RootCannotBeDeleted {
            get {
                return ResourceManager.GetString("RootCannotBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} B.
        /// </summary>
        public static string SizeBytes {
            get {
                return ResourceManager.GetString("SizeBytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        public static string SizeGigabytes {
            get {
                return ResourceManager.GetString("SizeGigabytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string SizeKilobytes {
            get {
                return ResourceManager.GetString("SizeKilobytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string SizeMegabytes {
            get {
                return ResourceManager.GetString("SizeMegabytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the SSH login.
        /// </summary>
        public static string SshLoginWhat {
            get {
                return ResourceManager.GetString("SshLoginWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown vault user..
        /// </summary>
        public static string VaultUserUnknown {
            get {
                return ResourceManager.GetString("VaultUserUnknown", resourceCulture);
            }
        }
    }
}
