//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberArkTerm.Core.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberArkTerm.Core.Localization.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account has no target address..
        /// </summary>
        public static string AccountHasNoAddress {
            get {
                return ResourceManager.GetString("AccountHasNoAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account has no user name..
        /// </summary>
        public static string AccountHasNoUser {
            get {
                return ResourceManager.GetString("AccountHasNoUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication cancelled..
        /// </summary>
        public static string AuthenticationCancelled {
            get {
                return ResourceManager.GetString("AuthenticationCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character not allowed in {0}: “{1}”..
        /// </summary>
        public static string CharacterNotAllowed {
            get {
                return ResourceManager.GetString("CharacterNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allowed machines.
        /// </summary>
        public static string ColumnAllowedMachines {
            get {
                return ResourceManager.GetString("ColumnAllowedMachines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ColumnCreated {
            get {
                return ResourceManager.GetString("ColumnCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string ColumnDomain {
            get {
                return ResourceManager.GetString("ColumnDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string ColumnPlatform {
            get {
                return ResourceManager.GetString("ColumnPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string ColumnSafe {
            get {
                return ResourceManager.GetString("ColumnSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ColumnServer {
            get {
                return ResourceManager.GetString("ColumnServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control characters are not allowed in the path..
        /// </summary>
        public static string ControlCharacterInPath {
            get {
                return ResourceManager.GetString("ControlCharacterInPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A folder cannot be moved into itself..
        /// </summary>
        public static string FolderIntoItself {
            get {
                return ResourceManager.GetString("FolderIntoItself", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string GroupNotSet {
            get {
                return ResourceManager.GetString("GroupNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to “{0}” not understood for {1} (yes or no expected).
        /// </summary>
        public static string ImportBadBoolean {
            get {
                return ResourceManager.GetString("ImportBadBoolean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string ImportColumnAddress {
            get {
                return ResourceManager.GetString("ImportColumnAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPM management.
        /// </summary>
        public static string ImportColumnCpm {
            get {
                return ResourceManager.GetString("ImportColumnCpm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        public static string ImportColumnPlatform {
            get {
                return ResourceManager.GetString("ImportColumnPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to safe.
        /// </summary>
        public static string ImportColumnSafe {
            get {
                return ResourceManager.GetString("ImportColumnSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string ImportColumnUser {
            get {
                return ResourceManager.GetString("ImportColumnUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The header has no “{0}” column (accepted names: {1})..
        /// </summary>
        public static string ImportMissingColumn {
            get {
                return ResourceManager.GetString("ImportMissingColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} missing.
        /// </summary>
        public static string ImportMissingValue {
            get {
                return ResourceManager.GetString("ImportMissingValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file contains no account..
        /// </summary>
        public static string ImportNoRow {
            get {
                return ResourceManager.GetString("ImportNoRow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ImportOutcomeCreated {
            get {
                return ResourceManager.GetString("ImportOutcomeCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not imported.
        /// </summary>
        public static string ImportOutcomeNotImported {
            get {
                return ResourceManager.GetString("ImportOutcomeNotImported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not sent.
        /// </summary>
        public static string ImportOutcomeNotSent {
            get {
                return ResourceManager.GetString("ImportOutcomeNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To create.
        /// </summary>
        public static string ImportOutcomePending {
            get {
                return ResourceManager.GetString("ImportOutcomePending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refused.
        /// </summary>
        public static string ImportOutcomeRefused {
            get {
                return ResourceManager.GetString("ImportOutcomeRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending….
        /// </summary>
        public static string ImportOutcomeSending {
            get {
                return ResourceManager.GetString("ImportOutcomeSending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ImportResultDetail {
            get {
                return ResourceManager.GetString("ImportResultDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string ImportResultLine {
            get {
                return ResourceManager.GetString("ImportResultLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ImportResultStatus {
            get {
                return ResourceManager.GetString("ImportResultStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file has more than {0} lines: split it..
        /// </summary>
        public static string ImportTooManyRows {
            get {
                return ResourceManager.GetString("ImportTooManyRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A quoted value is not closed..
        /// </summary>
        public static string ImportUnclosedQuote {
            get {
                return ResourceManager.GetString("ImportUnclosedQuote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid folder name..
        /// </summary>
        public static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The vault file keeps changing (another program is saving it). Try again in a moment..
        /// </summary>
        public static string KeePassBusy {
            get {
                return ResourceManager.GetString("KeePassBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The entry “{0}” was changed or deleted in the vault in the meantime. Reload the folder and try ag[rest of string was truncated].
        /// </summary>
        public static string KeePassConflict {
            get {
                return ResourceManager.GetString("KeePassConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The vault file is damaged ({0})..
        /// </summary>
        public static string KeePassCorrupted {
            get {
                return ResourceManager.GetString("KeePassCorrupted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong master password or key file..
        /// </summary>
        public static string KeePassInvalidKey {
            get {
                return ResourceManager.GetString("KeePassInvalidKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The vault's key derivation settings are too high to be computed here ({0})..
        /// </summary>
        public static string KeePassKdfTooCostly {
            get {
                return ResourceManager.GetString("KeePassKdfTooCostly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key file is damaged (its checksum doesn't match)..
        /// </summary>
        public static string KeePassKeyFileDamaged {
            get {
                return ResourceManager.GetString("KeePassKeyFileDamaged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is too large to be used as a key file..
        /// </summary>
        public static string KeePassKeyFileTooLarge {
            get {
                return ResourceManager.GetString("KeePassKeyFileTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key file version {0} is not supported..
        /// </summary>
        public static string KeePassKeyFileVersion {
            get {
                return ResourceManager.GetString("KeePassKeyFileVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is not a KeePass 2 vault (.kdbx)..
        /// </summary>
        public static string KeePassNotKdbx {
            get {
                return ResourceManager.GetString("KeePassNotKdbx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This vault uses an encryption that is not supported ({0}); AES-256 and ChaCha20 are..
        /// </summary>
        public static string KeePassUnsupportedCipher {
            get {
                return ResourceManager.GetString("KeePassUnsupportedCipher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This vault uses a key derivation that is not supported ({0})..
        /// </summary>
        public static string KeePassUnsupportedKdf {
            get {
                return ResourceManager.GetString("KeePassUnsupportedKdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KeePass format {0} is not supported (KDBX 3.1 and 4.x are)..
        /// </summary>
        public static string KeePassUnsupportedVersion {
            get {
                return ResourceManager.GetString("KeePassUnsupportedVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The vault was not saved: the new file failed verification, the original is untouched..
        /// </summary>
        public static string KeePassVerifyFailed {
            get {
                return ResourceManager.GetString("KeePassVerifyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string KindDatabase {
            get {
                return ResourceManager.GetString("KindDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string KindNetwork {
            get {
                return ResourceManager.GetString("KindNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string KindOther {
            get {
                return ResourceManager.GetString("KindOther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System language.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local vault file is damaged or was created by another Windows account..
        /// </summary>
        public static string LocalStoreDamaged {
            get {
                return ResourceManager.GetString("LocalStoreDamaged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local vault is locked..
        /// </summary>
        public static string LocalStoreLocked {
            get {
                return ResourceManager.GetString("LocalStoreLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no local vault yet..
        /// </summary>
        public static string LocalStoreMissing {
            get {
                return ResourceManager.GetString("LocalStoreMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local vault password must have at least {0} characters..
        /// </summary>
        public static string LocalStorePasswordTooShort {
            get {
                return ResourceManager.GetString("LocalStorePasswordTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong password for the local vault..
        /// </summary>
        public static string LocalStoreWrongPassword {
            get {
                return ResourceManager.GetString("LocalStoreWrongPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password for {0}:.
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        public static string PasswordPromptTitle {
            get {
                return ResourceManager.GetString("PasswordPromptTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the PSMP address.
        /// </summary>
        public static string PsmpAddressWhat {
            get {
                return ResourceManager.GetString("PsmpAddressWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid PVWA address: “{0}”..
        /// </summary>
        public static string PvwaAddressInvalid {
            get {
                return ResourceManager.GetString("PvwaAddressInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA address is required..
        /// </summary>
        public static string PvwaAddressRequired {
            get {
                return ResourceManager.GetString("PvwaAddressRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty response from the PVWA..
        /// </summary>
        public static string PvwaEmptyResponse {
            get {
                return ResourceManager.GetString("PvwaEmptyResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA must be reached over HTTPS: your credentials go through this connection..
        /// </summary>
        public static string PvwaHttpsRequired {
            get {
                return ResourceManager.GetString("PvwaHttpsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No session is open on the PVWA..
        /// </summary>
        public static string PvwaNoSession {
            get {
                return ResourceManager.GetString("PvwaNoSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from the PVWA: no session token received..
        /// </summary>
        public static string PvwaNoToken {
            get {
                return ResourceManager.GetString("PvwaNoToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA response is too long to be a password..
        /// </summary>
        public static string PvwaSecretTooLong {
            get {
                return ResourceManager.GetString("PvwaSecretTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA returned an HTML5 connection (PSM Gateway) instead of an RDP file..
        /// </summary>
        public static string RdpGatewayInstead {
            get {
                return ResourceManager.GetString("RdpGatewayInstead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from the PVWA{0}: no RDP file..
        /// </summary>
        public static string RdpUnexpected {
            get {
                return ResourceManager.GetString("RdpUnexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The root cannot be deleted..
        /// </summary>
        public static string RootCannotBeDeleted {
            get {
                return ResourceManager.GetString("RootCannotBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the server address.
        /// </summary>
        public static string ServerAddressWhat {
            get {
                return ResourceManager.GetString("ServerAddressWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} B.
        /// </summary>
        public static string SizeBytes {
            get {
                return ResourceManager.GetString("SizeBytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        public static string SizeGigabytes {
            get {
                return ResourceManager.GetString("SizeGigabytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string SizeKilobytes {
            get {
                return ResourceManager.GetString("SizeKilobytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string SizeMegabytes {
            get {
                return ResourceManager.GetString("SizeMegabytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the SSH login.
        /// </summary>
        public static string SshLoginWhat {
            get {
                return ResourceManager.GetString("SshLoginWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More than {0} files or folders: drag fewer at a time..
        /// </summary>
        public static string TooManyFiles {
            get {
                return ResourceManager.GetString("TooManyFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to check cancelled, file transferred.
        /// </summary>
        public static string TransferCheckCancelled {
            get {
                return ResourceManager.GetString("TransferCheckCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to incomplete file deleted.
        /// </summary>
        public static string TransferIncompleteDeleted {
            get {
                return ResourceManager.GetString("TransferIncompleteDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to incomplete file not deleted: {0}.
        /// </summary>
        public static string TransferIncompleteNotDeleted {
            get {
                return ResourceManager.GetString("TransferIncompleteNotDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the user name.
        /// </summary>
        public static string UserNameWhat {
            get {
                return ResourceManager.GetString("UserNameWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown vault user..
        /// </summary>
        public static string VaultUserUnknown {
            get {
                return ResourceManager.GetString("VaultUserUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server received {0} bytes instead of {1}: the file on the server is incomplete..
        /// </summary>
        public static string WriteIncomplete {
            get {
                return ResourceManager.GetString("WriteIncomplete", resourceCulture);
            }
        }
    }
}
