//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZillaTerm.Core.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZillaTerm.Core.Localization.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account has no target address..
        /// </summary>
        public static string AccountHasNoAddress {
            get {
                return ResourceManager.GetString("AccountHasNoAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The account has no user name..
        /// </summary>
        public static string AccountHasNoUser {
            get {
                return ResourceManager.GetString("AccountHasNoUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication cancelled..
        /// </summary>
        public static string AuthenticationCancelled {
            get {
                return ResourceManager.GetString("AuthenticationCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the server sent no certificate.
        /// </summary>
        public static string CertificateMissing {
            get {
                return ResourceManager.GetString("CertificateMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the certificate is not issued for this server name.
        /// </summary>
        public static string CertificateNameMismatch {
            get {
                return ResourceManager.GetString("CertificateNameMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the certificate is not issued by an authority trusted by Windows (self-signed, expired or revoked).
        /// </summary>
        public static string CertificateUntrusted {
            get {
                return ResourceManager.GetString("CertificateUntrusted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Character not allowed in {0}: “{1}”..
        /// </summary>
        public static string CharacterNotAllowed {
            get {
                return ResourceManager.GetString("CharacterNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allowed machines.
        /// </summary>
        public static string ColumnAllowedMachines {
            get {
                return ResourceManager.GetString("ColumnAllowedMachines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ColumnCreated {
            get {
                return ResourceManager.GetString("ColumnCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string ColumnDomain {
            get {
                return ResourceManager.GetString("ColumnDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string ColumnPlatform {
            get {
                return ResourceManager.GetString("ColumnPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string ColumnSafe {
            get {
                return ResourceManager.GetString("ColumnSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ColumnServer {
            get {
                return ResourceManager.GetString("ColumnServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control characters are not allowed in the path..
        /// </summary>
        public static string ControlCharacterInPath {
            get {
                return ResourceManager.GetString("ControlCharacterInPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is too large to be compared ({1}, at most {2})..
        /// </summary>
        public static string FileTooLargeToCompare {
            get {
                return ResourceManager.GetString("FileTooLargeToCompare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A folder cannot be moved into itself..
        /// </summary>
        public static string FolderIntoItself {
            get {
                return ResourceManager.GetString("FolderIntoItself", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificate of the FTPS server refused: connection stopped..
        /// </summary>
        public static string FtpCertificateDeclined {
            get {
                return ResourceManager.GetString("FtpCertificateDeclined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The FTP server does not offer encryption (TLS): connection in clear declined..
        /// </summary>
        public static string FtpCleartextDeclined {
            get {
                return ResourceManager.GetString("FtpCleartextDeclined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: file not found on the FTP server..
        /// </summary>
        public static string FtpNoSuchFile {
            get {
                return ResourceManager.GetString("FtpNoSuchFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The FTP server does not offer encryption (TLS), required by this entry (ftpes:// or ftps://)..
        /// </summary>
        public static string FtpTlsRequired {
            get {
                return ResourceManager.GetString("FtpTlsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer of {0} not completed by the FTP server..
        /// </summary>
        public static string FtpTransferFailed {
            get {
                return ResourceManager.GetString("FtpTransferFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string GroupNotSet {
            get {
                return ResourceManager.GetString("GroupNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to “{0}” not understood for {1} (yes or no expected).
        /// </summary>
        public static string ImportBadBoolean {
            get {
                return ResourceManager.GetString("ImportBadBoolean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string ImportColumnAddress {
            get {
                return ResourceManager.GetString("ImportColumnAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPM management.
        /// </summary>
        public static string ImportColumnCpm {
            get {
                return ResourceManager.GetString("ImportColumnCpm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        public static string ImportColumnPlatform {
            get {
                return ResourceManager.GetString("ImportColumnPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to safe.
        /// </summary>
        public static string ImportColumnSafe {
            get {
                return ResourceManager.GetString("ImportColumnSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string ImportColumnUser {
            get {
                return ResourceManager.GetString("ImportColumnUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The header has no “{0}” column (accepted names: {1})..
        /// </summary>
        public static string ImportMissingColumn {
            get {
                return ResourceManager.GetString("ImportMissingColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} missing.
        /// </summary>
        public static string ImportMissingValue {
            get {
                return ResourceManager.GetString("ImportMissingValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file contains no account..
        /// </summary>
        public static string ImportNoRow {
            get {
                return ResourceManager.GetString("ImportNoRow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ImportOutcomeCreated {
            get {
                return ResourceManager.GetString("ImportOutcomeCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not imported.
        /// </summary>
        public static string ImportOutcomeNotImported {
            get {
                return ResourceManager.GetString("ImportOutcomeNotImported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not sent.
        /// </summary>
        public static string ImportOutcomeNotSent {
            get {
                return ResourceManager.GetString("ImportOutcomeNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To create.
        /// </summary>
        public static string ImportOutcomePending {
            get {
                return ResourceManager.GetString("ImportOutcomePending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refused.
        /// </summary>
        public static string ImportOutcomeRefused {
            get {
                return ResourceManager.GetString("ImportOutcomeRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending….
        /// </summary>
        public static string ImportOutcomeSending {
            get {
                return ResourceManager.GetString("ImportOutcomeSending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ImportResultDetail {
            get {
                return ResourceManager.GetString("ImportResultDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string ImportResultLine {
            get {
                return ResourceManager.GetString("ImportResultLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ImportResultStatus {
            get {
                return ResourceManager.GetString("ImportResultStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file has more than {0} lines: split it..
        /// </summary>
        public static string ImportTooManyRows {
            get {
                return ResourceManager.GetString("ImportTooManyRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A quoted value is not closed..
        /// </summary>
        public static string ImportUnclosedQuote {
            get {
                return ResourceManager.GetString("ImportUnclosedQuote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid folder name..
        /// </summary>
        public static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The KeePass database file keeps changing (another program is saving it). Try again in a moment..
        /// </summary>
        public static string KeePassBusy {
            get {
                return ResourceManager.GetString("KeePassBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The entry “{0}” was changed or deleted in the KeePass database in the meantime. Reload the folder and try again..
        /// </summary>
        public static string KeePassConflict {
            get {
                return ResourceManager.GetString("KeePassConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The KeePass database file is damaged ({0})..
        /// </summary>
        public static string KeePassCorrupted {
            get {
                return ResourceManager.GetString("KeePassCorrupted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong master password or key file..
        /// </summary>
        public static string KeePassInvalidKey {
            get {
                return ResourceManager.GetString("KeePassInvalidKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key derivation settings of the KeePass database are too high to be computed here ({0})..
        /// </summary>
        public static string KeePassKdfTooCostly {
            get {
                return ResourceManager.GetString("KeePassKdfTooCostly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key file is damaged (its checksum doesn't match)..
        /// </summary>
        public static string KeePassKeyFileDamaged {
            get {
                return ResourceManager.GetString("KeePassKeyFileDamaged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is too large to be used as a key file..
        /// </summary>
        public static string KeePassKeyFileTooLarge {
            get {
                return ResourceManager.GetString("KeePassKeyFileTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key file version {0} is not supported..
        /// </summary>
        public static string KeePassKeyFileVersion {
            get {
                return ResourceManager.GetString("KeePassKeyFileVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is not a KeePass 2 database (.kdbx)..
        /// </summary>
        public static string KeePassNotKdbx {
            get {
                return ResourceManager.GetString("KeePassNotKdbx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This KeePass database uses an encryption that is not supported ({0}); AES-256 and ChaCha20 are..
        /// </summary>
        public static string KeePassUnsupportedCipher {
            get {
                return ResourceManager.GetString("KeePassUnsupportedCipher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This KeePass database uses a key derivation that is not supported ({0})..
        /// </summary>
        public static string KeePassUnsupportedKdf {
            get {
                return ResourceManager.GetString("KeePassUnsupportedKdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KeePass format {0} is not supported (KDBX 3.1 and 4.x are)..
        /// </summary>
        public static string KeePassUnsupportedVersion {
            get {
                return ResourceManager.GetString("KeePassUnsupportedVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The KeePass database was not saved: the new file failed verification, the original is untouched..
        /// </summary>
        public static string KeePassVerifyFailed {
            get {
                return ResourceManager.GetString("KeePassVerifyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string KindDatabase {
            get {
                return ResourceManager.GetString("KindDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string KindNetwork {
            get {
                return ResourceManager.GetString("KindNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string KindOther {
            get {
                return ResourceManager.GetString("KindOther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System language.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local vault file is damaged or was created by another Windows account..
        /// </summary>
        public static string LocalStoreDamaged {
            get {
                return ResourceManager.GetString("LocalStoreDamaged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local vault is locked..
        /// </summary>
        public static string LocalStoreLocked {
            get {
                return ResourceManager.GetString("LocalStoreLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no local vault yet..
        /// </summary>
        public static string LocalStoreMissing {
            get {
                return ResourceManager.GetString("LocalStoreMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local vault password must have at least {0} characters..
        /// </summary>
        public static string LocalStorePasswordTooShort {
            get {
                return ResourceManager.GetString("LocalStorePasswordTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong password for the local vault..
        /// </summary>
        public static string LocalStoreWrongPassword {
            get {
                return ResourceManager.GetString("LocalStoreWrongPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password for {0}:.
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        public static string PasswordPromptTitle {
            get {
                return ResourceManager.GetString("PasswordPromptTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} refused).
        /// </summary>
        public static string ProtocolFallback {
            get {
                return ResourceManager.GetString("ProtocolFallback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the PSMP address.
        /// </summary>
        public static string PsmpAddressWhat {
            get {
                return ResourceManager.GetString("PsmpAddressWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid PVWA address: “{0}”..
        /// </summary>
        public static string PvwaAddressInvalid {
            get {
                return ResourceManager.GetString("PvwaAddressInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA address is required..
        /// </summary>
        public static string PvwaAddressRequired {
            get {
                return ResourceManager.GetString("PvwaAddressRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty response from the PVWA..
        /// </summary>
        public static string PvwaEmptyResponse {
            get {
                return ResourceManager.GetString("PvwaEmptyResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA must be reached over HTTPS: your credentials go through this connection..
        /// </summary>
        public static string PvwaHttpsRequired {
            get {
                return ResourceManager.GetString("PvwaHttpsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No session is open on the PVWA..
        /// </summary>
        public static string PvwaNoSession {
            get {
                return ResourceManager.GetString("PvwaNoSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from the PVWA: no session token received..
        /// </summary>
        public static string PvwaNoToken {
            get {
                return ResourceManager.GetString("PvwaNoToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA response is too long to be a password..
        /// </summary>
        public static string PvwaSecretTooLong {
            get {
                return ResourceManager.GetString("PvwaSecretTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA returned an HTML5 connection (PSM Gateway) instead of an RDP file..
        /// </summary>
        public static string RdpGatewayInstead {
            get {
                return ResourceManager.GetString("RdpGatewayInstead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from the PVWA{0}: no RDP file..
        /// </summary>
        public static string RdpUnexpected {
            get {
                return ResourceManager.GetString("RdpUnexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The root cannot be deleted..
        /// </summary>
        public static string RootCannotBeDeleted {
            get {
                return ResourceManager.GetString("RootCannotBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server closed the SCP connection during the upload: {0}..
        /// </summary>
        public static string ScpClosedByServer {
            get {
                return ResourceManager.GetString("ScpClosedByServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the server closed the SCP channel as soon as the scp command was sent: {0}.
        /// </summary>
        public static string ScpRefusedCommand {
            get {
                return ResourceManager.GetString("ScpRefusedCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to refused earlier in this tab for a file of {0}.
        /// </summary>
        public static string ScpRefusedEarlier {
            get {
                return ResourceManager.GetString("ScpRefusedEarlier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the server closed the SCP channel when the file ({0}) was announced: {1}.
        /// </summary>
        public static string ScpRefusedHeader {
            get {
                return ResourceManager.GetString("ScpRefusedHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the server address.
        /// </summary>
        public static string ServerAddressWhat {
            get {
                return ResourceManager.GetString("ServerAddressWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The shared list is being modified by someone else: try again in a moment..
        /// </summary>
        public static string ServerListBusy {
            get {
                return ResourceManager.GetString("ServerListBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is not a ZillaTerm server list..
        /// </summary>
        public static string ServerListInvalid {
            get {
                return ResourceManager.GetString("ServerListInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is an export of My servers, not a shared list: import it instead..
        /// </summary>
        public static string ServerListNotShared {
            get {
                return ResourceManager.GetString("ServerListNotShared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This server list was written by a newer version of ZillaTerm (format {0}): update ZillaTerm[rest of string was truncated].
        /// </summary>
        public static string ServerListTooNew {
            get {
                return ResourceManager.GetString("ServerListTooNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} B.
        /// </summary>
        public static string SizeBytes {
            get {
                return ResourceManager.GetString("SizeBytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        public static string SizeGigabytes {
            get {
                return ResourceManager.GetString("SizeGigabytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string SizeKilobytes {
            get {
                return ResourceManager.GetString("SizeKilobytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string SizeMegabytes {
            get {
                return ResourceManager.GetString("SizeMegabytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the SSH login.
        /// </summary>
        public static string SshLoginWhat {
            get {
                return ResourceManager.GetString("SshLoginWhat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More than {0} files or folders: drag fewer at a time..
        /// </summary>
        public static string TooManyFiles {
            get {
                return ResourceManager.GetString("TooManyFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to check cancelled, file transferred.
        /// </summary>
        public static string TransferCheckCancelled {
            get {
                return ResourceManager.GetString("TransferCheckCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to incomplete file deleted.
        /// </summary>
        public static string TransferIncompleteDeleted {
            get {
                return ResourceManager.GetString("TransferIncompleteDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to incomplete file not deleted: {0}.
        /// </summary>
        public static string TransferIncompleteNotDeleted {
            get {
                return ResourceManager.GetString("TransferIncompleteNotDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected version number: {0}.
        /// </summary>
        public static string UpdateBadVersion {
            get {
                return ResourceManager.GetString("UpdateBadVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The downloaded archive does not match SHA256SUMS.txt (expected {0}, got {1}): it was deleted..
        /// </summary>
        public static string UpdateChecksumMismatch {
            get {
                return ResourceManager.GetString("UpdateChecksumMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The archive is missing from SHA256SUMS.txt: it cannot be checked..
        /// </summary>
        public static string UpdateNoChecksum {
            get {
                return ResourceManager.GetString("UpdateNoChecksum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This version has no Windows archive or no SHA256SUMS.txt file..
        /// </summary>
        public static string UpdateNoPackage {
            get {
                return ResourceManager.GetString("UpdateNoPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The archive is unexpectedly large: download stopped..
        /// </summary>
        public static string UpdateTooLarge {
            get {
                return ResourceManager.GetString("UpdateTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} refused by the server: {1}. {2}: {3}.
        /// </summary>
        public static string UploadRefusedThenFailed {
            get {
                return ResourceManager.GetString("UploadRefusedThenFailed", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Unknown CyberArk Vault user..
        /// </summary>
        public static string VaultUserUnknown {
            get {
                return ResourceManager.GetString("VaultUserUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VNC password refused. {0}.
        /// </summary>
        public static string VncAuthFailed {
            get {
                return ResourceManager.GetString("VncAuthFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VNC server closed the connection..
        /// </summary>
        public static string VncClosedByServer {
            get {
                return ResourceManager.GetString("VncClosedByServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This server does not speak the VNC protocol (RFB): check the address and the port (5900 by default)..
        /// </summary>
        public static string VncNotRfb {
            get {
                return ResourceManager.GetString("VncNotRfb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VNC server asks for a password and the entry has none..
        /// </summary>
        public static string VncPasswordRequired {
            get {
                return ResourceManager.GetString("VncPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected data from the VNC server: connection closed..
        /// </summary>
        public static string VncProtocolError {
            get {
                return ResourceManager.GetString("VncProtocolError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VNC server refuses the connection: {0}.
        /// </summary>
        public static string VncRefused {
            get {
                return ResourceManager.GetString("VncRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VNC server announces a screen of {0} × {1}: too large..
        /// </summary>
        public static string VncScreenTooLarge {
            get {
                return ResourceManager.GetString("VncScreenTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VNC server offers no authentication supported by ZillaTerm (offered: {0}). ZillaTerm ac[rest of string was truncated].
        /// </summary>
        public static string VncSecurityUnsupported {
            get {
                return ResourceManager.GetString("VncSecurityUnsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No VNC answer from the server within 30 seconds: check the address and the port (5900 by default)..
        /// </summary>
        public static string VncTimeout {
            get {
                return ResourceManager.GetString("VncTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported VNC protocol version: {0}.
        /// </summary>
        public static string VncUnsupportedVersion {
            get {
                return ResourceManager.GetString("VncUnsupportedVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server received {0} bytes instead of {1}: the file on the server is incomplete..
        /// </summary>
        public static string WriteIncomplete {
            get {
                return ResourceManager.GetString("WriteIncomplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to replaced by a symbolic link while the rights were being changed: left as is.
        /// </summary>
        public static string ChangedDuringChmod {
            get {
                return ResourceManager.GetString("ChangedDuringChmod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA did not send the password but an unexpected response ({0}): a sign-in page (SSO) or a maintenance page may be in the way. Log on again, then try again..
        /// </summary>
        public static string PvwaUnexpectedSecretResponse {
            get {
                return ResourceManager.GetString("PvwaUnexpectedSecretResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to current permissions unknown: only a full mode (all rwx boxes set or cleared) can be applied.
        /// </summary>
        public static string PermissionsUnknown {
            get {
                return ResourceManager.GetString("PermissionsUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection cancelled: the server key was not accepted..
        /// </summary>
        public static string HostKeyRefused {
            get {
                return ResourceManager.GetString("HostKeyRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to “{0}” already exists: choose another name (nothing was replaced)..
        /// </summary>
        public static string RenameTargetExists {
            get {
                return ResourceManager.GetString("RenameTargetExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file {0} is too large for a list of sessions ({1} MB at most)..
        /// </summary>
        public static string MigrationFileTooLarge {
            get {
                return ResourceManager.GetString("MigrationFileTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file cannot be read: {0}.
        /// </summary>
        public static string MigrationUnreadable {
            get {
                return ResourceManager.GetString("MigrationUnreadable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder not found: {0}.
        /// </summary>
        public static string MigrationFolderMissing {
            get {
                return ResourceManager.GetString("MigrationFolderMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is not a registry export (.reg)..
        /// </summary>
        public static string MigrationNotRegFile {
            get {
                return ResourceManager.GetString("MigrationNotRegFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is not a {0} file..
        /// </summary>
        public static string MigrationWrongFile {
            get {
                return ResourceManager.GetString("MigrationWrongFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is fully encrypted. Export the connections again without full-file encryption, then import that copy..
        /// </summary>
        public static string MigrationEncryptedFile {
            get {
                return ResourceManager.GetString("MigrationEncryptedFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string MigrationReady {
            get {
                return ResourceManager.GetString("MigrationReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} possible accounts: check the one chosen.
        /// </summary>
        public static string MigrationCheck {
            get {
                return ResourceManager.GetString("MigrationCheck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not imported: no account in the PVWA for {0}.
        /// </summary>
        public static string MigrationNoAccount {
            get {
                return ResourceManager.GetString("MigrationNoAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not imported: {0} connections are not handled.
        /// </summary>
        public static string MigrationUnsupported {
            get {
                return ResourceManager.GetString("MigrationUnsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already in My servers, folder {0}.
        /// </summary>
        public static string MigrationAlreadyPresent {
            get {
                return ResourceManager.GetString("MigrationAlreadyPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already in My servers.
        /// </summary>
        public static string MigrationAlreadyPresentRoot {
            get {
                return ResourceManager.GetString("MigrationAlreadyPresentRoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not imported: unchecked.
        /// </summary>
        public static string MigrationExcluded {
            get {
                return ResourceManager.GetString("MigrationExcluded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        public static string MigrationImported {
            get {
                return ResourceManager.GetString("MigrationImported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string MigrationColFolder {
            get {
                return ResourceManager.GetString("MigrationColFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string MigrationColProtocol {
            get {
                return ResourceManager.GetString("MigrationColProtocol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PVWA account.
        /// </summary>
        public static string MigrationColAccount {
            get {
                return ResourceManager.GetString("MigrationColAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string MigrationColConnection {
            get {
                return ResourceManager.GetString("MigrationColConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder in My servers.
        /// </summary>
        public static string MigrationColTarget {
            get {
                return ResourceManager.GetString("MigrationColTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MigrationColResult {
            get {
                return ResourceManager.GetString("MigrationColResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refused by the server: wrong password or code. Attempt {0} of {1}: check it (Caps Lock?) before sending, because too many failures can lock the account..
        /// </summary>
        public static string AuthenticationRefusedRetry {
            get {
                return ResourceManager.GetString("AuthenticationRefusedRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password or code refused {0} times: connection abandoned so that the account is not locked. Check the password, then connect again..
        /// </summary>
        public static string AuthenticationRefusedFinal {
            get {
                return ResourceManager.GetString("AuthenticationRefusedFinal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA address may only contain the server name, then a port and a path if needed: no “name@” before the server, no space or “\”, no accented letters or letters from another alphabet (an international name is written in its “xn--” form)..
        /// </summary>
        public static string PvwaAddressSuspicious {
            get {
                return ResourceManager.GetString("PvwaAddressSuspicious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA answered with a redirection (HTTP {0}) to {1}. It is not followed, so that your password and session are never sent to another address: check the PVWA address in the Settings (exact server name and path to PasswordVault)..
        /// </summary>
        public static string PvwaRedirectNotFollowed {
            get {
                return ResourceManager.GetString("PvwaRedirectNotFollowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to “{0}” is a special file (device, named pipe or socket): it can be neither opened nor downloaded, because reading it would never end or would block the server..
        /// </summary>
        public static string SpecialFileRefused {
            get {
                return ResourceManager.GetString("SpecialFileRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file nests folders more than {0} levels deep: it is refused as damaged..
        /// </summary>
        public static string MigrationTooDeep {
            get {
                return ResourceManager.GetString("MigrationTooDeep", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This FTP server used to encrypt its connections (TLS) and no longer offers it: connection stopped, the password was not sent..
        /// </summary>
        public static string FtpTlsRemoved {
            get {
                return ResourceManager.GetString("FtpTlsRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection cancelled: the VNC password was not sent..
        /// </summary>
        public static string VncPasswordNotSent {
            get {
                return ResourceManager.GetString("VncPasswordNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Remote Desktop server does not accept TLS encryption: its identity cannot be checked, the password of the entry is not sent to it..
        /// </summary>
        public static string RdpNoTls {
            get {
                return ResourceManager.GetString("RdpNoTls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server did not answer like a Remote Desktop server: check the address and the port (3389 by default)..
        /// </summary>
        public static string RdpNotRdp {
            get {
                return ResourceManager.GetString("RdpNotRdp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Remote Desktop server refused the connection (code {0})..
        /// </summary>
        public static string RdpNegotiationRefused {
            get {
                return ResourceManager.GetString("RdpNegotiationRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No answer from the Remote Desktop server within 30 seconds: check the address and the port (3389 by default)..
        /// </summary>
        public static string RdpProbeTimeout {
            get {
                return ResourceManager.GetString("RdpProbeTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TLS negotiation with the Remote Desktop server failed: {0}.
        /// </summary>
        public static string RdpTlsFailed {
            get {
                return ResourceManager.GetString("RdpTlsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} PVWA message: {1}.
        /// </summary>
        public static string ErrorWithPvwaMessage {
            get {
                return ResourceManager.GetString("ErrorWithPvwaMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Details: {1}.
        /// </summary>
        public static string ErrorWithDetail {
            get {
                return ResourceManager.GetString("ErrorWithDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA refused the user name or the password. Check them (and Caps Lock) before trying again: after several failures, CyberArk suspends the account..
        /// </summary>
        public static string PvwaBadCredentials {
            get {
                return ResourceManager.GetString("PvwaBadCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your CyberArk account is suspended or disabled (too many failed sign-ins, or by an administrator). Ask the CyberArk team to reactivate it..
        /// </summary>
        public static string PvwaUserSuspended {
            get {
                return ResourceManager.GetString("PvwaUserSuspended", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your CyberArk password has expired: change it on the PVWA web page, then sign in here with the new one..
        /// </summary>
        public static string PvwaPasswordExpired {
            get {
                return ResourceManager.GetString("PvwaPasswordExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This account needs an approved request (dual control): request access on the PVWA web page and wait for the approval, then try again..
        /// </summary>
        public static string PvwaDualControl {
            get {
                return ResourceManager.GetString("PvwaDualControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CyberArk requires a valid ticket for this account: check the ticketing system and the ticket number (“Ticket” fields), then try again..
        /// </summary>
        public static string PvwaTicketRequired {
            get {
                return ResourceManager.GetString("PvwaTicketRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CyberArk requires a reason for this account: enter it in the “Reason” field, then try again..
        /// </summary>
        public static string PvwaReasonRequired {
            get {
                return ResourceManager.GetString("PvwaReasonRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This connection component is not set up for the platform of the account: choose another one in “Advanced options…” (PSM component)..
        /// </summary>
        public static string PvwaComponentNotConfigured {
            get {
                return ResourceManager.GetString("PvwaComponentNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This account already exists in this safe..
        /// </summary>
        public static string PvwaAlreadyExists {
            get {
                return ResourceManager.GetString("PvwaAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your CyberArk session has expired: sign in again..
        /// </summary>
        public static string PvwaSessionExpired {
            get {
                return ResourceManager.GetString("PvwaSessionExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CyberArk refused this action: your account does not have the rights it needs on this safe. Ask a manager of the safe (“Safe members…” shows your rights)..
        /// </summary>
        public static string PvwaForbidden {
            get {
                return ResourceManager.GetString("PvwaForbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not found in CyberArk (deleted, or your rights were removed): refresh the list (F5)..
        /// </summary>
        public static string PvwaNotFound {
            get {
                return ResourceManager.GetString("PvwaNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PVWA ran into an error: try again in a moment. If it persists, give this message to the CyberArk team..
        /// </summary>
        public static string PvwaServerError {
            get {
                return ResourceManager.GetString("PvwaServerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The SSH server refused the authentication. Check the password (and Caps Lock) before trying again; through the PSMP it is your CyberArk password, and several failures suspend your account..
        /// </summary>
        public static string SshAuthenticationRefused {
            get {
                return ResourceManager.GetString("SshAuthenticationRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server closed the connection without answering in SSH: check the address and the port, or try again in a moment..
        /// </summary>
        public static string SshNoSshAnswer {
            get {
                return ResourceManager.GetString("SshNoSshAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server did not answer in time: check the address, the port and your network access (VPN, firewall), then try again..
        /// </summary>
        public static string NetworkTimeout {
            get {
                return ResourceManager.GetString("NetworkTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server name not found (DNS): check the address, or your connection to the company network (VPN)..
        /// </summary>
        public static string NetworkHostNotFound {
            get {
                return ResourceManager.GetString("NetworkHostNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server refuses connections on this port: check the address and the port, and that the service is running there..
        /// </summary>
        public static string NetworkRefused {
            get {
                return ResourceManager.GetString("NetworkRefused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection was cut by the server or the network: reconnect..
        /// </summary>
        public static string NetworkConnectionLost {
            get {
                return ResourceManager.GetString("NetworkConnectionLost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to machine {0}.
        /// </summary>
        public static string FieldMachine {
            get {
                return ResourceManager.GetString("FieldMachine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to safe {0}.
        /// </summary>
        public static string FieldSafe {
            get {
                return ResourceManager.GetString("FieldSafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to platform {0}.
        /// </summary>
        public static string FieldPlatform {
            get {
                return ResourceManager.GetString("FieldPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to domain {0}.
        /// </summary>
        public static string FieldDomain {
            get {
                return ResourceManager.GetString("FieldDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name {0}.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to any machine.
        /// </summary>
        public static string AnyMachine {
            get {
                return ResourceManager.GetString("AnyMachine", resourceCulture);
            }
        }
    }
}
